#!/bin/bash
#  _____________________________________________________
# +=[ Version 0.2 - beta                               
# +=[ BY: AstralSecHaxor From Brazil                   
# +=[ YouTube: https://youtube.com/@AstralSec_Haxor    
# +=[ Github: https://github.com/AstralSecHaxor/LazyUser
#  —————————————————————————————————————————————————————

if [ "$(uname -o | tr '[:upper:]' '[:lower:]')" == "android" ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
else
  conf_dir="/etc"
fi

if [ -e /usr/lib/sudo ]; then
  sudo python3 "$conf_dir/LazyUser/lazyuser.py"
else
  python3 "$conf_dir/LazyUser/lazyuser.py"
fi

exit